server:
  port: 1313

database:
  uri: "<YOUR_MONGODB_URI>"

gemini:
  apiKey: "YOUR_GEMINI_API_KEY"

jwt:
  secret: "local_dev_secret_key_123"
  expiry: 1440

smtp:
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  senderEmail: ""
  senderName: "DebateAI Team"

googleOAuth:
  clientID: "YOUR_GOOGLE_CLIENT_ID"
